name: sanity_testing
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: install deps
        run: npm ci

      - uses: actions/cache@v3.3.2
        id: npm-cache
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: install Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - run: pip install -r requirements.txt

      - name: allure install
        run: npm install allure-commandline

      - name: run tests
        run: pytest --alluredir ./dashboard/

    archive:
      need: deploy
      runs-on: ubuntu-latest
      steps:
        - name: Get project code
          uses: actions/checkout@v3
        - name: Install Deps
          run: npm ci

        - name: Upload artifacts
          uses: actions/upload-artifact@v3
          with:
            name: allure_dashboard
            path: ./results/
      deploy:
        needs: archive
        runs-on: ubuntu-latest
        steps:
          - name: Get build artifacts
            uses: actions/download-artifact@v3
            with:
              name: build-files